### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by HumanG33k** [matrix-construct/construct#1]
I just try to compile on debian testing. 
I follow the readme but maybe i miss something.

First i have to remove the  CXX=g++-6 on CXX=g++-6 ./configure --prefix=$PWD/build.

[configure.log](https://github.com/matrix-construct/construct/files/2363617/configure.log)
[make.log](https://github.com/matrix-construct/construct/files/2363620/make.log)

**Comment by mujx** [comment]
Construct currently only supports `gcc 6`. In your build logs the std library from `gcc 8` is invoked as you can see at the end of the log.

```
In file included from /usr/include/c++/8/functional:59,
                 from stdinc.h:57,
                 from ircd.pic.h:15:
/usr/include/c++/8/bits/std_function.h:128:11: note: declaration of ‘class std::function<void(ircd::buffer::const_buffer, ircd::buffer::const_buffer) noexcept>’
     class function;
           ^~~~~~~~
```

Although I'm not that familiar with Debian, the following should work on Ubuntu to set `gcc 6` as the default compiler.

```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10                                        
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10                                       
                                                                                                                   
sudo update-alternatives --set gcc "/usr/bin/gcc-6"                                                          
sudo update-alternatives --set g++ "/usr/bin/g++-6" 
```

There is also a dockerfile in `tools/` which creates a working dev environment.

**Comment by HumanG33k** [comment]
Do you know why it’s not working without g++ 6 ? Maybe i can fix that.

**Comment by jevolk** [comment]
> Do you know why it’s not working without g++ 6 ? Maybe i can fix that.

Too late. g++-8 support now added by fad454f3b1b9 through a2160443ca22 on master:

1. Pull master.

2. Reopen here if problem.

(there's still a lot of trivial warning noise).
