### ISSUE TITLE
Large !control room command outputs are incorrectly truncated

### ISSUE THREAD

**Issue by jevolk** [matrix-construct/construct#101]
Bad JSON; newline '\n' in the JSON.

**Comment by yangm97** [comment]
Seems that what was supposed to be a newline is actually a `` token (Sublime says it is <0x1b>).

**Comment by jevolk** [comment]
> Seems that what was supposed to be a newline is actually a `�` token (Sublime says it is <0x1b>).

Thanks! Good catch.
