### ISSUE TITLE
Room mentions don't show up as pills before joining them

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#111]
Could be either because I hadn't joined yet or because my server hadn't joined the room yet. After joining, mentions for said room became pilled.

**Comment by jevolk** [comment]
The most efficient way for this to be fixed is to include a description of what is required for _Riot_ to generate a pill. If you know of anything more specific the server should be doing, or witnessed any errors that interfered with something, that would be ideal to squash this quickly.

**Comment by yangm97** [comment]
Happens on matrix.org accounts.
