### ISSUE TITLE
Automated backfill needs to be more aggressive

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#140]
For instance, when a user is kicked from a room, init backfill won't fetch the leave event.

**Comment by jevolk** [comment]
Are you sure this isn't a c2s-sync issue? Is the problem with the server synchronizing the room from other servers (and specifically on server restart) or is the problem with the client not receiving the data?

**Comment by yangm97** [comment]
From the console, `room get !roomid m.room.member @mxid raw` returns a "join" membership, so it doesn't look c2s related. 

I am assuming my server missed the kick event while it was offline, so it would be ideal if at least initial backfill could fetch that. We possibly could have hooks for failed message events too, although that can be tricky/impossible seeing as synapse likes to soft fail.

**Comment by jevolk** [comment]
Sounds good. I think when the state synchronization phase is straightened out during initial backfill this will be covered.

**Comment by jevolk** [comment]
Fixed by e4d517415b45252b6d23c4507e27c5bacf6acd79 ee23dae92a3ac0ba33560e06574c453a2e99a51a

**Comment by jevolk** [comment]
Hmmm I think you meant a different kind of aggressive. Well, if this is still an issue lmk.
