### ISSUE TITLE
invalid json unicode messages break stuff (Signature was forged or corrupt)

### ISSUE THREAD

**Issue by grinapo** [matrix-construct/construct#158]
(dumped from the channel; by davo)

Some messages can't federate due to invalid signature:

`Invalid signature for server yetanothernerd.xyz with key ed25519:8fO1vxo5: Unable to verify signature for yetanothernerd.xyz: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt` ☹︎

I bet what's happening is that Construct is dumping strings it gets from clients as is, with no regard for whether they're valid canonical JSON (Unicode escapes and all).

[link](https://matrix.to/#/!AAAANTUiY1fBZ230:zemos.net/$15923111459jOBQX:vovo.id.au?via=zemos.net&via=matrix.org&via=privacytools.io)

**Comment by jevolk** [comment]
Yes, it appears Synapse unescapes the unicode for its hash preimage. I think this was overlooked when working on #152.
