### ISSUE TITLE
client/unstable/room_keys/keys: buffer_overrun :Insufficient buffer of 0.00 B (0); required at least 1.00 B (1)

### ISSUE THREAD

**Issue by grinapo** [matrix-construct/construct#160]
I believe I have set all config variables I have fiddled with to default, but still see these all the time:
```
client:74972 h1 1:1 HTTP 500 Internal Error `/_matrix/client/unstable/room_keys/keys?version=1581348' :buffer_overrun :Insufficient buffer of 0.00 B (0); required at least 1.00 B (1)
```
what variables are connected to this endpoint? Shall I fiddle with config or is it still a bug?

**Comment by jevolk** [comment]
> I believe I have set all config variables I have fiddled with to default

FYI you can type the command `conf diff` to explore what items are different from default.

> what variables are connected to this endpoint? Shall I fiddle with config or is it still a bug?

There is probably no specific conf item related to this. The endpoint serves data directly from an event stored in your user room. Conveniently, you can find this event by typing `event 1581348` (which is the value of the `?version=` query parameter. There is probably something in that event's content which is tripping up the response mechanism. I'm not sure if the event contains private material so be careful before you paste anything here, but the first thing you can do is explore the characteristics of that event's content and see if anything stands out. According to the response code https://github.com/matrix-construct/construct/blob/master/modules/client/room_keys/version.cc#L269 those properties are copied to the client; are they present and well-formed?

If nothing else works and you are up to the task, you can place a `__builtin_debugtrap()` or set a gdb breakpoint around https://github.com/matrix-construct/construct/blob/master/include/ircd/spirit.h#L336 and explore the variables in the frames leading up to where that is thrown (ideally back to the room_keys/version endpoint's frame).

**Comment by grinapo** [comment]
just for the record it's here as well (apart from what I wrote on matrix):
```
      (event_id) :$4tN1CwcQceHF79pOphvk7KglHSxqM54NuV7zyInmL7Y
         room_id :!2m7wSU6wKX6VijASRJc8KiP2m77C:construct.grin.hu
          sender :@grin:construct.grin.hu
          origin :construct.grin.hu
           depth :23180
            type :ircd.room_keys.version
origin_server_ts :Wed, 13 May 2020 23:59:50 +0200 (1589407190240)
         content :2 keys; 442 bytes.
          [hash] :sha256 5Vcqt9SdqjtN2LRskBj7VQfj2SiOaKk6ZOd2pRJqO1Y
     [signature] :construct.grin.hu ed25519:YK74ZQkT 
    [auth event] :$B4uThVLpOWqfsyOdxytdoxv7yOA4NO0CeJeaIsRRDm4
    [prev_event] :$Z5DpXgGF6qgRpuDC5GLyYdT0x9X_UHTjzizUGRJLR5c
       [content] :STRING     40 bytes :algorithm
       [content] :OBJECT    375 bytes :auth_data

        SEQUENCE  1581348
       JSON SIZE  994.00 B (994)
          CACHED   _json content event_id room_id             
      REFERENCES  2
   REFERENCED BY  1

--> AUTH                43 !2m7wSU6wKX6VijASRJc8KiP2m77C:construct.grin.hu $B4uThVLpOWqfsyOdxytdoxv7yOA4NO0CeJeaIsRRDm4 2020/04/24 21:29:39 0 m.room.create "" * * @ircd:construct.grin.hu 
--> PREV           1581347 !2m7wSU6wKX6VijASRJc8KiP2m77C:construct.grin.hu $Z5DpXgGF6qgRpuDC5GLyYdT0x9X_UHTjzizUGRJLR5c 2020/05/13 23:59:50 23179 AP ircd.account_data m.megolm_backup.v1 * * @grin:construct.grin.hu 
---                1581348 !2m7wSU6wKX6VijASRJc8KiP2m77C:construct.grin.hu $4tN1CwcQceHF79pOphvk7KglHSxqM54NuV7zyInmL7Y 2020/05/13 23:59:50 23180 AP ircd.room_keys.version * * * @grin:construct.grin.hu 
```

**Comment by grinapo** [comment]
It is always the **same** event!
And keeps repeated continuously.

**Comment by grinapo** [comment]
Okay so I guess this one was resolved by

- upgrading to the fixed rocksdb version a few months back
- recreating (export+import) the database

If you need it please reopen.
