### ISSUE TITLE
Spec violation on the "scale" method

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#161]
Expected behaviour: 
From https://matrix.org/docs/spec/client_server/latest#thumbnails 
> "scale" maintains the original aspect ratio of the image

Actual behaviour: 
For instance, given the `width=800&height=32` flags, the image gets stretched to fill the width, ignoring the original aspect ratio.

**Comment by jevolk** [comment]
Do you have a link to a specific image that didn't render correctly in the client? This code might not be to spec, but the spec might also violate the spec, I'm sure you know what I mean :) :+1:

**Comment by yangm97** [comment]
It happens with any image. i.e. https://yetanothernerd.xyz/_matrix/media/r0/thumbnail/m.trnsz.com/MyLnOGhbaWgOzRSpYjtHoTgQ?width=800&height=32 shouldn't return a 800x32 image since that wouldn't keep the original aspect ratio but it does just that.

**Comment by grinapo** [comment]
Indeed the spec says **"Servers MUST NOT upscale thumbnails under any circumstance"**.

(It also says _"Servers MUST NOT return a smaller thumbnail than requested, unless the original content makes that impossible."_)

(I fail to understand how the server shall select between "crop" and "scale" methods. but that's life.)
