### ISSUE TITLE
User-friendlier build/setup/tuning documentation

### ISSUE THREAD

**Issue by gprst** [matrix-construct/construct#163]
Greetings ! Before discovering compiling on arm64 devices was not yet possible, I tried to install required and optional dependencies on my Ubuntu-based OS, and discovered I didn't know what packages I actually needed.

I am really not used to build from source and far from having a C++ background, thus I was kind of lost when looking for Boost, Sodium, Magic, jemalloc, GraphicsMagick and ICU (which one turne out to be already installed) packages, since the packages aren't named as such with apt, and I didn't know whether I needed the dev version of the packages.

Do you think it might be possible you name the actual needed packages to build the project ? It would be great.

**Comment by jevolk** [comment]
Yes this is a good idea. A convenient package list (full shell copy-pasta preferably) is something many projects provide upfront.

> Do you think it might be possible you name the actual needed packages to build the project ? It would be great.

At the moment there's actually a crude package list you can extract from the [Dockerfile](https://github.com/matrix-construct/construct/blob/master/docker/ubuntu/base/Dockerfile) for Ubuntu. Also I believe there's another graphicsmagick package which isn't listed there: `libgraphicsmagick-q16-3` IIRC.

**Comment by gprst** [comment]
Of course, I haven't thought about the Dockerfile, thank you for the recall.

Also, there was something else that I found confusing : in the BUILD page, you suggest to set the `--prefix` option to something like `~/.local` (which doesn't work, as an absolute path is required), then write `./configure --prefix=$PWD/build`, which would result in building in a `build` directory _inside the git project_, although you specifically advice _not_ to set the prefix path inside the git project. I think one should be corrected, either the command in « Standalone procedure », or the advice.

**Comment by gprst** [comment]
Well
I think there's something you should do about your wiki ; I tried to fork it, but it seemed not to be possible. Thus I tried to just, edit the page, [and I could](https://github.com/matrix-construct/construct/wiki/BUILD/_compare/e91416ad6fa4c59df1210f5c3a3afaf739c68433...bb9e2bf42a3b680da28106aef364a94af591e568), without any warning nor write restrictions. I added the two first bullet points of the « Compatibility Primer » section, please revise as you see fit.

**Comment by grinapo** [comment]
> I think there's something you should do about your wiki ; I tried to fork it, but it seemed not to be possible. 

You should familiarise yourself with **github**: that's their problem.

> Thus I tried to just, edit the page, and I could

That is the whole point of a wiki, ain't it? ;-)

>  I added the two first bullet points of the « Compatibility Primer » section, please revise as you see fit.

Looks fine to me, thanks for the update.

**Comment by gprst** [comment]
> That is the whole point of a wiki, ain't it? ;-)

Don't your fear anyone might want to abuse how easy it is to edit your wiki ?

**Comment by danger89** [comment]
Yup.. what maybe a docker image could help as well? Thanks!

**Comment by gprst** [comment]
> Yup.. what maybe a docker image could help as well? Thanks!

Such an image already exists, and this is what I based my contribution uppon.

> EDIT: You can create an automate build pipeline and spit out a docker image that others can easily install / manage. (At least the dockerfile it there, now an image would be nice 👍 )

I'm unsure whether this is relevant regarding the issue, that is clearly about documentation, rather that about a Docker image.

I added a clear list of all required packages for Construct to build, I am closing this issue.

**Comment by danger89** [comment]
OK, I don't want to rude here, but a dockerfile isn't the same as shipping the actual images.

I only found synapse in docker hub, but not construct:

https://hub.docker.com/r/matrixdotorg/synapse/

**Comment by yangm97** [comment]
@danger89 I have plans for documenting container usage and automating the push of container images to https://hub.docker.com/r/matrixconstruct/construct 

You can poke me at https://matrix.to/#/#construct:zemos.net if you have any questions

**Comment by jevolk** [comment]
@danger89 I just don't think this has been done yet, but should be. Can you open another issue for this? I have the dockerfiles built at https://hub.docker.com/repository/docker/jevolk/construct but these are intended for continuous-integration, so Construct still has to be compiled in them (see .appveyor.yml).

Can you open another issue and describe what you expected (i.e. what you wanted to see here but didn't).

**Comment by yangm97** [comment]
Opened #167 to keep track of this.
