### ISSUE TITLE
Accepting/declining room invites from remote servers doesn't work

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#18]
If your remote server happens to be synapse, the invite will get stuck forever.

**Comment by jevolk** [comment]
- Declining fixed by 1542d1a0cae83f2d39e8dd19d342ef297b86b90f
- Accepting fixed by 7d8913ca55de0f69447cccc3ea5fe041519d76c7

Will not work on existing rooms because the create event format has changed. Must test with newly created room.

**Comment by yangm97** [comment]
Happening again.

**Comment by jevolk** [comment]
> Happening again.

Was this under any specific circumstances or does this operation unconditionally fail now (regressed)?

**Comment by yangm97** [comment]
Regressed. Though I've only tested inviting on newly created rooms.

**Comment by jevolk** [comment]
This issue ends up being the result of other broken things. It will probably be perpetually re-opened and closed again for different reasons. Since this issue has been open again, invites have gone through at least an entire cycle of fixed -> broken -> fixed. We will surely see you again.
