### ISSUE TITLE
Arch Linux Build Fails

### ISSUE THREAD

**Issue by bigOconstant** [matrix-construct/construct#187]
I've been trying to follow the build guide but the build fails with 

```bash

error: Could not read profile default.profdata: No such file or directory
```

To make it easier to reproduce, I've made a Dockerfile that demonstrates it. 

https://github.com/bigOconstant/constructDockerBuild

Can someone take a look at [this dockerfile](https://github.com/bigOconstant/constructDockerBuild/blob/master/Dockerfile) to see if they can find where I'm going wrong with the build?

**Comment by jevolk** [comment]
Merging with #185 thanks for reporting!
