### ISSUE TITLE
Start non-interactively using Docker

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [matrix-construct/construct#190]
I am looking for a way to start Construct in a non-interactive way using the docker image.

The goal is to deploy a minimal Construct in [FluffyChat](https://gitlab.com/famedly/fluffychat)'s CI in order to test any basic feature against any existing Matrix homeserver implementation. As of now, we did not reach at deploying Construct without any user interaction in the CI resulting in only having integration tests against Conduit, Dendrite and Synapse.

Instructions for non-interactive startup would be helpful

**Comment by jevolk** [comment]
This is near the top of the short-list. It _may_ be possible to use `-execute` arguments to run the interactive commands right now, but proper conf-items/env-vars are really in order here.

#188

**Comment by jevolk** [comment]
See: https://github.com/matrix-construct/construct/wiki/SETUP#non-interactive
