### ISSUE TITLE
Suppress .well-known not found errors or reply those requests

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#61]

**Comment by jevolk** [comment]
FTR: These are logged at level `DERROR` and not `ERROR` so they'll only be seen when compiled in debug mode from `--enable-debug` or if `--with-log-level=` is set to show that level (see: https://github.com/matrix-construct/construct/blob/master/doc/BUILD.md). Level `DERROR` can also be toggled with the console command `log level`.

Even though the homeserver doesn't have to respond to .well-known I've implemented a handler for it in f15769ea0ee056dad9d778e8acb428b4f0d4cd68.
