### ISSUE TITLE
Clients don't offer to jump up the scrollback to where you last read

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#64]

**Comment by jevolk** [comment]
This works for me after `m.fully_read` was fixed and sent down /sync in room account_data, which was like two days ago. Is this still not working after that? Perhaps not 100% of the time?

**Comment by yangm97** [comment]
For me it looked like it was only fetching replies from messages that were already synced. Gotta try the latest builds.

**Comment by jevolk** [comment]
Confirmed working with OP
