### ISSUE TITLE
Can't set room message delivery priorities (noisy, mentions only, etc)

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#67]

**Comment by jevolk** [comment]
Is this related to #63 ?

**Comment by yangm97** [comment]
Nope, this refers to actually setting the preference. It will not stick.

**Comment by jevolk** [comment]
I clicked the preference in Riot and I was hit with
```
HTTP PUT `/_matrix/client/r0/pushrules/global/room/!AAAANTUiY1fBZ230%3Azemos.net'
HTTP PUT `/_matrix/client/r0/pushrules/global/room/!AAAANTUiY1fBZ230%3Azemos.net/enabled'
```
so it seems that won't stick without #63

**Comment by yangm97** [comment]
Guess riot is not receiving whatever it wants back then. When I click any option, it quickly goes back to the default option (at least visually).

**Comment by jevolk** [comment]
Implemented with Push Notifications suite.
