### ISSUE TITLE
Need a Continuous Integration solution.

### ISSUE THREAD

**Issue by jevolk** [matrix-construct/construct#68]
Need advice for a CI that will compile on the following (and combinations thereof): GCC 7 & 8, clang, linux (at least ubuntu 18.04, 18.10, maybe 16.04), mingw windows, freebsd, amd64, arm64...

**Comment by yangm97** [comment]
I think CircleCI checks those boxes.

**Comment by yangm97** [comment]
This also may be useful https://github.com/dockcross/dockcross

**Comment by mujx** [comment]
CircleCI lets you bring your own docker image so it should work, but the free plan allows 1000 minutes per month. So you would need an image with everything pre-installed (rocksdb, boost, gcc etc) to not go over the limit.

For windows I suggest appveyor which also offers ubuntu16.04 & 18.04 for linux builds.

**Comment by jevolk** [comment]
Solved by 959fdb8fd3cbde3ac30bd7e3927ece4500f8b6cb; though a build matrix for the multiple platforms still has to be devised.

Thanks @mujx !!!
