### ISSUE TITLE
Downloaded files sometimes come with the original header on it's body, making the file invalid

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#71]
![image](https://user-images.githubusercontent.com/4412002/55728012-a4e16e00-59e9-11e9-8d8b-d2d0310ca599.png)
![image](https://user-images.githubusercontent.com/4412002/55728027-aad74f00-59e9-11e9-93c2-09cc3a7aab74.png)
![image](https://user-images.githubusercontent.com/4412002/55728055-b6c31100-59e9-11e9-822d-30900c126853.png)

**Comment by jevolk** [comment]
Fixed; related:
31eab7d2354d9b4284a92a41864797dee200fc72
7d4cf45f018f5737775acdf01924c1272d4cd69b
55e9bc87e180037cd3b9fde4a428ed1dc4c0fb55
b7855f15bb1ab76f5e1a48d4df5c478ec71285f0
