### ISSUE TITLE
It appears that rotation metadata confuses the thumbnailer, generating a distorted thumbnail

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#90]
Event for reference
https://matrix.to/#/!MKREUBPbabkbWvCRxk:matrix.org/$1564235234135765KOxGP:t2bot.io?via=matrix.org&via=t2bot.io&via=tomesh.net

Thumbnail
<img width="371" alt="image" src="https://user-images.githubusercontent.com/4412002/62001560-e8abd080-b0c9-11e9-981d-31a83811d53e.png">

Full image
<img width="865" alt="image" src="https://user-images.githubusercontent.com/4412002/62001589-5c4ddd80-b0ca-11e9-8d6b-a56425bc0382.png">

**Comment by jevolk** [comment]
@yangm97 Need the original file causing the anomaly

**Comment by yangm97** [comment]
Can't reproduce the issue, even when using the same file as the event at the OP. One of the attempts resulted in a distorted thumbnail from Synapse, so I'll assume there is something wrong with that file in particular.
