### ISSUE TITLE
Compilation error in invite.cc - invalid initialization of reference

### ISSUE THREAD

**Issue by SuperRoboWizard** [matrix-construct/construct#93]
During the `make install` phase, compilation halts with the following error:
```
client/rooms/invite.cc: In function ‘ircd::m::id::event::buf ircd::m::invite_foreign(const ircd::m::event&)’:
client/rooms/invite.cc:239:2: error: invalid initialization of reference of type ‘const ircd::json::object&’ from expression of type ‘<brace-enclosed initializer list>’
  239 |  };
      |  ^
```
This *sounds* like an easy fix, but only being a novice in C++ this goes waaayyy over my head.

**Comment by jevolk** [comment]
Do you have any information about your toolchain? Linux distro? GCC version?

**Comment by SuperRoboWizard** [comment]
Distro is Manjaro (Arch derivative) version 18.0.4 "Illyria". GCC is version 9.1.0.

I'm not sure what you mean by "information about my toolchain" (I'm just a hobbyist), but I have binutils version 2.32-2, glibc version 2.29-3.1, and kernel version 5.1.18-1 if that's helpful.

**Comment by jevolk** [comment]
Very helpful, thanks.
